#!/bin/bash

### The variables ###
API="https://wikimedia.org/api/rest_v1"
header="[redacted]"
article=""    # Name of the Wiki article you'd like to search for. Note, format must have capital first letter, and underscores replacing spaces. For example "bass guitar" would have to be formatted as "Bass_Guitar"
outputName=$(echo "$article" | sed 's/_/ /g')
start="20230101" #Start Date - Format yyyyMMdd
fin="20230623" #End Date - Format yyyyMMdd
csvpath="$HOME/localScripts/$article.csv"

### The script ###

## The API request
apicall() {
    curl \
        -H "$header" \
        "$API/metrics/pageviews/per-article/en.wikipedia.org/all-access/user/$article/daily/$start/$fin" | \
    jq '.items[] | [.timestamp,.views]'
}

## The CSV output
topLine="date,views" #This will be the first line of the CSV script to identify the columns

csv() {
    printf "%s\n%s\n\n" "$outputName Views" "$topLine" > "$csvpath"
    #printf "%s\n\n" "$topLine" > "$csvpath"
    apicall | jq -r @csv >> "$csvpath"
}

## the execution
csv
